### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by khuang-citylift** [adam-26/react-script-tag#19]
Hi, 

I believe this is only meant for React Web apps and NOT React Native apps, is that correct?
I am using this in my React Native application and I am getting:
`Invariant Violation: View config not found for name script.`

Thanks,
Kevin

**Comment by adam-26** [comment]
Hi,

Yes, thats correct - it was written for Web apps. If you want to use it in a native app you'll need to fork the code and make the required changes.

Adam.
