### ISSUE TITLE
Breaks navigation

### ISSUE THREAD

**Issue by dylannirvana** [adam-26/react-script-tag#25]
Sorry to bother, but it is so close. Almost works. It loads fine at first, but then breaks (goes blank) when I navigate to another page. It is not being removed is the problem I imagine? I tried regular componentDidMount but that did not render script at all.
`import ScriptTag from 'react-script-tag'`
`render() {    
          return (
              <div>
                     <ScriptTag isHydrating={true} data-uid="e9274113f5" src="https://astounding-creator-7935.ck.page/e9274113f5/index.js" />  
            </div>
        )
    }`

**Comment by adam-26** [comment]
I suggest looking at the source code to understand how the component works.

Have you tried using a regular script tag?

Good luck!
